CirclePlan/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('', include('accounts.urls')),

    path('members/', include('members.urls')),

    path('circles/', include('attendance.urls')),
   
    path('yashuvim/', include('yashuvim.urls')),

    path('admin/', admin.site.urls),

    path('admin_circles/', include('circles.urls')),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path


from . import views
app_name="accounts"
urlpatterns = [
    path('',views.index, name='index'), 
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),



]

circles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.adminCircles, name='adminCircles'),
    path('<int:circle_id>/',views.adminCircle, name='adminCircle'),
    path('<int:circle_id>/<int:meeting_id>/',views.adminMeeting, name='adminMeeting'),
    #path('<int:circle_id>/<int:pk>/att/', views.MeetingViewSet.as_view({'post':'att'}), name='MeetingViewSet'),
    path('search' , views.search, name= 'search'),
] 

templates/partials/_alerts.html
{% if messages %}
    {%for message in messages%}
        <div id="message" calss ="container">
            <div class="alert alert-{{ message.tags }} alert-dismissible text-center" role ="alert">
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span></button>
                <strong>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                        Error
                    {% else %}
                        {{ message.tags|title }}
                    {% endif %}
                </strong>
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

templates/partials/_footer.html
<footer id="main-footer" class=" bg-primary text-white text-center">
    Copyright &copy;
    <span class="year" ></span> CirclePlan
  </footer>

templates/partials/_navbar.html
{% load static%}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary sticky-top">
    <div class="container">
      <a class="light-navbar-brand" href="">
        <img src="{% static 'img/logo.png' %}" class="logo" alt="">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">

          <li
            {% if '/' == request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif%} >
            <a class="nav-link" href=""></a>
          </li>

          <li >
           <a ></a>
          </li>

          <li>
          <a></a>
         </li>

        </ul>

        <ul class="navbar-nav ml-auto">
          {%if user.is_authenticated %}
          <li
            {% if 'dashboard' in request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif %}
            >


          </li>
          <li class="nav-item mr-3">
              <a href="javascript:{document.getElementById('logout').submit()}"
              class="nav-link">
                <i class="fas fa-sign-out-alt"> </i> התנתק
            </a>
            <form action="{% url 'accounts:logout' %}" method="POST" id="logout"> 
                {% csrf_token %}
              <input type="hidden">
            </form>
          </li>


          {%else %}
            <li
            {% if 'register' in request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif%}
            >

            </li>
            <li
            {% if 'register' in request.path %}
              class="nav-item active mr-3"
            {% else %}
              class="nav-item mr-3"
            {% endif%}
            >
              <a class="nav-link" href="{% url 'admin:index' %}">
                <i class="fas fa-sign-in-alt"></i>

                כניסת מנהל</a>
            </li>
          {%endif%}
        </ul>
      </div>
    </div>
  </nav>

templates/partials/_topbar.html
<!-- Top Bar -->
<section id="top-bar" class="p-3">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <i class="fas fa-phone"></i> (617)-555-5555
        </div>
        <div class="col-md-4">
          <i class="fas fa-envelope-open"></i> contact@btrealestate.co
        </div>
        <div class="col-md-4">
          <div class="social text-right">
            <a href="#">
              <i class="fab fa-twitter"></i>
            </a>
            <a href="#">
              <i class="fab fa-facebook"></i>
            </a>
            <a href="#">
              <i class="fab fa-linkedin"></i>
            </a>
            <a href="#">
              <i class="fab fa-instagram"></i>
            </a>
            <a href="#">
              <i class="fab fa-pinterest"></i>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>