CirclePlan/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from django.conf.urls import url

urlpatterns = [
    path('', include('accounts.urls')),

    path('members/', include('members.urls')),

    path('circles/', include('attendance.urls')),
   
    path('yashuvim/', include('yashuvim.urls')),

    path('admin/', admin.site.urls),

    path('admin_circles/', include('circles.urls')),
    
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path


from . import views
app_name="accounts"
urlpatterns = [
    path('',views.index, name='index'), 
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
    path('dashboard', views.dashboard, name='dashboard'),



]

circles/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.adminCircles, name='adminCircles'),
    path('<int:circle_id>/',views.adminCircle, name='adminCircle'),
    path('<int:circle_id>/<int:meeting_id>/',views.adminMeeting, name='adminMeeting'),
    #path('<int:circle_id>/<int:pk>/att/', views.MeetingViewSet.as_view({'post':'att'}), name='MeetingViewSet'),
    path('search' , views.search, name= 'search'),
] 

accounts/views.py
from django.shortcuts import render , redirect
from django.contrib import messages , auth
from django.contrib.auth.models import User




def index(request):
     if request.method == 'POST':
          username = request.POST['username']
          password = request.POST['password']
          user = auth.authenticate(username=username,password=password)

          if user is not None:
               auth.login(request,user)
               messages.success(request,'התחברת בהצלחה')
               return redirect('/circles')

          else:
               messages.error(request,'פרטי משתמש אינם נוכנים ')
               return redirect('/')

     else:

          auth.logout(request)
          return render(request,'accounts/index.html')



def logout(request):
     if request.method == 'POST':
          auth.logout(request)
          messages.success(request,'התנתקת בהצלחה')
          return redirect('http://127.0.0.1:8000/')


def dashboard(request):
     return render(request,'accounts/dashboard.html')



def register(request):
     if request.method == 'POST':
          first_name = request.POST['first_name']
          last_name = request.POST['last_name']
          username = request.POST['username']
          email = request.POST['email']
          password = request.POST['password']
          password2 = request.POST['password2']

          # Cehck if password match
          if password == password2:
               #Cehck username
               if User.objects.filter(username = username).exists():
                    messages.error(request,' שם משתמש תפוס נסה אחר')
                    return redirect('register')
               else:
                    if User.objects.filter(email = email).exists():
                         messages.error(request,'מייל תפוס נסה אחר')
                         return redirect('register')
                    else:
                         # not taken
                         user = User.objects.create_user(username=username,password=password
                         ,email=email,first_name=first_name,last_name=last_name)

                         #wtiout login after register
                         #auth.login(request,user)
                         #messages.success(request, 'Your are now logged in')
                         #return redirect('index')

                         #with login after register
                         user.save()
                         messages.success(request,'נרשמת בהצלחה')
                         return redirect('index')


          else:
               messages.error(request,'הסיסמה לא תואמת ')
               return redirect('register')
     else:
          return render(request,'accounts/register.html')

templates/accounts/dashboard.html
  {% extends 'base.html'%}
  {%block title %} | Dashboard{% endblock %}
  {% block content %}

    <!-- Breadcrumb -->
  <section id="showcase-inner" class="py-4 text-green">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12 dar"  >
          <h1 class="display-5">לוח ניהול פעילויות</h1>
          <h2 class="lead"></b>נהל פעיליות ודווח נוכחות</b></h2>
        </div>
      </div>
    </div>
  </section>


 <!--Alerts--> 
 {% include 'partials/_alerts.html' %}

  <!-- Breadcrumb -->
  <section id="bc" class="mt-4">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            
              <i class="fas fa-home"></i>ראשי</a>
          </li>
          <!--<li class="breadcrumb-item active"> Dashboard</li>-->
        </ol>
      </nav>
    </div>
  </section>


  <section id="dashboard" class="py-2">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>שלום,  {{user}}</h2>
    
          
            <h5> רשימת החוגים שלך :</h5>

            {% if circles  %}
                <table class="table col-md-12">
                  <thead>
                    <tr>
                     
                      <th scope="col-md-4 ">שם חוג</th>
                      <th scope="col-md-4">שם ישוב</th>
                      

                      <th></th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for circle in circles %}
                      {% if circle.instructor == user  %}
                    
                        <tr>
                         
                          <td>{{ circle.title }}</td>
                          <td>{{ circle.yashuv }}</td>
                          
                          <td>

                    
                        <a class="btn btn-light col-md-12" href="{% url 'meeting' circle.id meeting.id %}">כנס כאן</a>
                          
                          </td>
                        </tr>
                      {% endif %}
                    {% endfor %}
                  </tbody>
                </table>
            {% else %}
            <p></p>
            <p> אין כרגע חוג שאתה מדריך </p>
            {% endif %}

            <div class="row">
              <div class="col-md-12">
      
      
                    {% if circles.has_other_pages %}
      
                      <ul class="pagination">
                          {% if circles.has_previous %}
                            <li class="page_item"> 
                              <a href="?page={{circles.previous_page_number}}" class="page-link"> &laquo; </a>
                            </li>
                          {% else %}
                            <li class ="page-item disabled">
                              <a  class="page-link">  &laquo; </a>
                            </li>
                          {%endif%}  
                          {% for i in circles.paginator.page_range %}
                             {% if circles.number == i %}
                                <li class ="page-item active">
                                  <a class="page-link">  {{i}} </a>
                                </li> 
                             {% else%}
                              <li class ="page-item ">
                                  <a href="?page={{i}}" class="page-link"> {{i}} </a>
                              </li>
                             {% endif %}
                          {% endfor %}
                          {% if listings.has_next %}
                              <li class="page_item"> 
                                <a href="?page={{circles.next_page_number}}" class="page-link"> &raquo; </a>
                              </li>
                          {% else %}
                            <li class ="page-item disabled">
                              <a  class="page-link">  &laquo; </a>
                            </li>
                          {%endif%}  
                      </ul>
      
                    {%endif%}
      
              </div>
            </div>


        </div>
      </div>
    </div>
  </section>

 


  {% endblock %}

templates/accounts/index.html
{% extends 'base.html' %}
{% load humanize %}

{%block title %} | Welcome {% endblock %}

{% block content %}

<div class="hero-image">


<section  id="login" class="bg-light py-5" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 mx-auto">
        <div class="card">
          <div class="card-header bg-primary text-white">
            <h4 dir="ltr" >
              <i  class="fas fa-sign-in-alt " ></i> כניסה</h4>
          </div>
          <div class="card-body" style="margin:0;">

            <!---Alerts -->

              {% include 'partials/_alerts.html' %}

              <form action="{%url 'accounts:index' %}" method="post" id="form_attend">
                  {% csrf_token %}

              <div class="form-group">
                <label for="username">שם המשתמש</label>
                <input type="text" name="username" class="form-control" required>
              </div>

              <div class="form-group">
                <label for="password2">סיסמה</label>
                <input type="password" name="password" class="form-control" required>
              </div>

              <input type="submit" value="Login" class="btn btn-secondary btn-block">
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
</div>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{%block title %} | Login {% endblock %}
{% block content %}



{% endblock %}

templates/accounts/register.html
{% extends 'base.html' %}
{%block title %} | Register New Account {% endblock %}
{% block content %}

<section id="register" class="bg-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-md-6 mx-auto">
          <div class="card">
            <div class="card-header bg-primary text-white">
              <h4>
                <i class="fas fa-user-plus"></i> Register</h4>
            </div>
            <div class="card-body">
              <!---Alerts -->


                {% include 'partials/_alerts.html' %}
                <form action="{% url 'att2' assc.id %}" method="post">
                    {% csrf_token %}
                <div class="form-group">
                  <label for="first_name">First Name</label>
                  <input type="text" name="first_name" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="last_name">Last Name</label>
                  <input type="text" name="last_name" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="username">Username</label>
                  <input type="text" name="username" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="email">Email</label>
                  <input type="email" name="email" class="form-control" required>
                </div>
                <div class="form-group">
                  <label for="password2">Password</label>
                  <input type="password" name="password" class="form-control" required>
                </div> 
                <div class="form-group">
                  <label for="password">Confirm Password</label>
                  <input type="password" name="password2" class="form-control" required>
                </div>
                <input type="submit" value="Register" class="btn btn-secondary btn-block">
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}